## The pair of functions below allow you to cache the inverse
## of a matrix. The first function, makeCacheMatrix, creates
## a special "matrix" object that can cache its inverse. 
## The second function, cacheSolve, can compute the inverse of 
## the special "matrix" returned by makeCacheMatrix. If the
## inverse has already been calculated (and not changed), then 
## cacheSolve retrieves the inverse from the cache.

## This function creates a special "matrix" object that can 
## cache its inverse.
## Argument x: Object of class matrix.
## Returns: An object of class list which contains a list of 
## functions required to store and retrieve the special matrix.
makeCacheMatrix <- function(x = matrix()) {
        
        ## Sets i to NULL to prepare a variable required to
        ## store the inverse of a matrix. Additionally, serves
        ## as a check to verify if the inverse has already been 
        ## generated (i = !NULL) or not (i = NULL).
        i <- NULL
        
        ## Creates a function called "set" which is used to
        ## store a desired matrix. Argument y: desired matrix.
        ## Sets i to NULL to prepare a variable required to store
        ## the inverse of the matrix.
        set <- function(y) {
                x <<- y
                i <<- NULL
        }
        
        ## Creates a function called "get" which is used to 
        ## retrieve the stored matrix.
        ## Returns: the stored matrix, x.
        get <- function() x
        
        ## Creates a function called "SetInverse" which is called by
        ## the function cacheSolve to store the inverse of a matrix.
        ## Argument inverse: the inverse matrix. Stores the inverse 
        ## matrix in the variable i.
        setInverse <- function(inverse) i <<- inverse
        
        ## Creates a function called "getInverse" which is called by  
        ## the function cacheSolve to retrieve the inverse of 
        ## the stored matrix. Returns the inverse matrix, i, if it has
        ## been stored previously. Otherwise, returns NULL.
        getInverse <- function() i
        
        ## Returns a list of functions as the "special" matrix object.
        list(set = set, get = get,
             setInverse = setInverse,
             getInverse = getInverse)
}


## This function computes the inverse of the special "matrix" 
## generated by makeCacheMatrix(). If the inverse has already 
## been calculated (and the matrix has not changed), then 
## cacheSolve() retrieves the inverse from the cache. 
## Argument x: object of class list.
## Returns: inverse of the stored matrix. 
cacheSolve <- function(x, ...) {
        
        ## Subsets the list x to call the getInverse function to
        ## retrieve the inverse of the stored matrix. If the
        ## inverse exists (was cached; not NULL), then displays the message, 
        ## "getting cached inverse" and returns the stored inverse, i.
        ## Otherwise, subsets the list x to call the get function to
        ## retrieve the stored matrix (below).
        i <- x$getInverse()
        if(!is.null(i)) {
                message("getting cached inverse")
                return(i)
        }
        
        ## Subsets the list x to call the get function to 
        ## retrieve the stored matrix.
        matrix <- x$get()
        
        ## Calls the solve function with the retrieved matrix as its
        ## argument to generate the inverse of the matrix and store in i.
        i <- solve(matrix, ...)
        
        ## Subsets the list x to call the setInverse function to store
        ## the calculated inverse. Once stored in i, 
        ## i becomes "not null" and the if statement above will be
        ## executed in order to avoid the repeat caculation of the inverse.
        x$setInverse(i)
        
        ## Returns the inverse of the stored matrix.
        i
}
